name: drought-ml
channels: [conda-forge, defaults]
dependencies:
  - python=3.11
  - numpy
  - pandas
  - xarray
  - netcdf4
  - scikit-learn
  - pytorch
  - torchvision
  - matplotlib
  - shap
  - pip
  - pip:
      - pyyaml
      - tensorflow==2.16.*
