seed: 42
data:
  file: "data/sample/sample_timeseries.csv" 
  id_col: "GridID" 
  year_col: "Year" 
  month_col: "Month"
  target: "SRI"
  features:['PRE', 'Tmax', "Tmin","Cropland", "Forest","Grassland","Shrubland", "Impervious", "Wetland", "Water", "SOI", "NAO", "NESO", "DMI", "PDO","IM","WYMI","WNPMI","Nightlight", "POP", "GDP", "NDVI", 
                 "SM", "evp","ElvAvg", "SlopeAvg"]
  freq: "M"
  lookback: 0
split:
  method: "per_grid_random"   
  ratios:
    train: 0.75              
    test: 0.25                
  val_within_train: 0.0      
  shuffle: true              
  random_state: 1  

xgb:
  colsample_bytree: 0.95
  max_depth: 15
  gamma: 0.1
  learning_rate: 0.2
  min_child_weight: 3
  subsample: 0.9
  random_state: 1
  
 cv:
  enable: true
   nfold: 5 
 
